[project]
name = "modules-and-interfaces"
version = "0.1.0"
description = "An minimum reproduceable example of a modular approach to service architecture in Python"
readme = "README.md"
authors = [
    { name = "Toby Johnson", email = "tobyojohnson@proton.me" }
]
requires-python = ">=3.14"
dependencies = [
    "hvac>=2.4.0",
    "pydantic-settings>=2.6.0",
    "redis>=8.1.0",
]

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
module-name = "modkit"
