[project]
name = "modules-and-interfaces"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Toby Johnson", email = "toby.johnson@capgemini.com" }
]
requires-python = ">=3.14"
dependencies = [
    "hvac>=2.4.0",
    "redis>=8.1.0",
]

[project.scripts]
modules-and-interfaces = "modules_and_interfaces:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
